version: '3'

services:
#  mongodb:
#    image: mongo@latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "mongo"
#      MONGO_INITDB_ROOT_PASSWORD: "mongo"
#    ports:
#      - 27017:27017

  brain-overflow-backend:
    build: .
    command: uvicorn src.app:app --host 0.0.0.0 --port 8005 --reload
    ports:
      - 8005:8005
    volumes:
      - .:/app
#    environment:
#      MONGODB_URI: "mongodb://mongo:27017"
##    depends_on:
##      - mongodb